FROM alpine:3.9

# persistent / runtime deps
RUN apk update \
    && apk upgrade 

RUN apk add php7-fpm 
        
# ensure www-data user exists
RUN set -eux; \
        addgroup -g 82 -S www-data; \
        adduser -u 82 -D -S -G www-data www-data
# 82 is the standard uid/gid for "www-data" in Alpine
# https://git.alpinelinux.org/aports/tree/main/nginx/nginx.pre-install?h=3.9-stable

RUN set -eux; \
        mkdir -p "/usr/local/etc/php/conf.d"; \
        [ ! -d /var/www/html ]; \
        mkdir -p /var/www/html; \
        chown www-data:www-data /var/www/html; \
        chmod 777 /var/www/html

RUN set -eux; \
        cd /usr/local/etc; \
        if [ -d php-fpm.d ]; then \
                sed 's!=NONE/!=!g' php-fpm.conf.default | tee php-fpm.conf > /dev/null; \
                touch php-fpm.d/www.conf; \
        else \
                # PHP 5.x doesn't use "include=" by default, create simple config PHP 7+
                mkdir php-fpm.d; \
                touch php-fpm.d/www.conf; \
                { \
                        echo '[global]'; \
                        echo 'include=etc/php-fpm.d/*.conf'; \
                } | tee php-fpm.conf; \
        fi; \
        { \
                echo '[global]'; \
                echo 'error_log = /proc/self/fd/2'; \
                echo; \
                echo 'log_limit = 8192'; \
                echo; \
                echo '[www]'; \
                echo '; if we send this to /proc/self/fd/1, it never appears'; \
                echo 'access.log = /proc/self/fd/2'; \
                echo; \
                echo 'clear_env = no'; \
                echo; \
                echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
                echo 'catch_workers_output = yes'; \
                echo 'decorate_workers_output = no'; \
        } | tee php-fpm.d/docker.conf; \
        { \
                echo '[global]'; \
                echo 'daemonize = no'; \
                echo; \
                echo '[www]'; \
                echo 'listen = 9000'; \
        } | tee php-fpm.d/zz-docker.conf

# Override stop signal to stop process gracefully

STOPSIGNAL SIGQUIT

EXPOSE 9000

CMD ["php-fpm7"]


